### ISSUE TITLE
create_resource checks for update? on related records

### ISSUE THREAD

**Issue by billxinli** [venuu/jsonapi-authorization#29]
Hi:

Thank you for this library! 

I have a question with regarding to create_resource, why does it check on `update?` instead of `show?`

For example, I may allow a user to reference an object that the user only have read only access to?

      def create_resource(source_class, related_records)
        ::Pundit.authorize(user, source_class, 'create?')

        related_records.each do |record|
          ::Pundit.authorize(user, record, 'update?')
        end
      end

**Comment by valscion** [comment]
Hi! Thanks for reaching out.

https://github.com/venuu/jsonapi-authorization/issues/14#issuecomment-199175736 could answer your question a bit, on why it is so. Mainly we just wanted to map JSONAPI operations to Rails/Pundit default actions so that it would be easier to try out this gem in any existing application.

> An option we initially considered when writing this gem was to create an Authorizer which calls much more specific actions on the policies, e.g. `create_relationship?`. That would come pretty close to what you are suggesting, and make it easier to define more granular permissions on the policy level.
> 
> One reason we didn't, was to avoid adding too much complexity for new users trying out jsonapi-authorization.
> 
> Another reason is that, to answer the question of `create_relationship?`, you usually need both the source record and the related record. Passing multiple records to a policy is [explicitly discouraged](https://github.com/elabs/pundit#additional-context) by Pundit, so we'd have to create our own wrapper or other convention there. Or create some custom non-Pundit type of policies.
> 
> With that being said, I would _love_ for us to create a more sophisticated Authorizer, and include it in the project as a suggested option to use when you reach the limits of DefaultPunditAuthorizer. That would give us all a simple default setup, with a common convention for more advanced, granular control.

We're looking into solutions for #15 which essentially would cover this issue as well. In the meantime, you are free to create a different authorizer to suit your needs as specified in the [`README.md` Configuration section](https://github.com/venuu/jsonapi-authorization/blob/v0.6.1/README.md#configuration). 

Do note that the API for authorizers might change as we reach for a solution for these issues.

**Comment by valscion** [comment]
Please see #30 for a possible solution to this problem. Any input in there is greatly appreciated!
