### ISSUE TITLE
Using resource_klass instead of _model_class for policy

### ISSUE THREAD

**Issue by thibaudgg** [venuu/jsonapi-authorization#8]
As an application could have different policies for models and API resources, I think it would be better to use the `resource_klass` instead of the `_model_class` in `AuthorizingOperationsProcessor`. 

By default we could make `Resource.policy_class` returns `_model_class.policy_class` so the current behaviour wouldn't change, but it would be easier to overwrite. Something like that:

``` ruby
module JSONAPI
  module Authorization
    module PunditPolicyClassResource
      extend ActiveSupport::Concern

      module ClassMethods
        def policy_class(_context)
           _model_class.policy_class
        end
      end
    end
  end
end
```

We have many way to access our resources (public, client, user, admin, ...) so it would be nice if we can have one namespace policy per access. If we can overwrite the `Resource#policy_class` with the `context` info it would be great.

What do you think?

**Comment by valscion** [comment]
Having different policy classes based on context seems a bit against the Pundit architecture. Shouldn't you do those checks on the policy level instead of inferring the entire policy class from the current user or something?

Having a `self.policy_class` on the resource overridable seems like a good idea. I wouldn't want to add any parameters to it, though. [This is how Pundit itself approaches the issue](https://github.com/elabs/pundit#manually-specifying-policy-classes) — no parameters in the `policy_class` method.

If you want to delegate authorization to different classes, wouldn't it be more precise to have a general base policy for a resource which delegates authorization checks to more special classes based on the current user? Something like:

```ruby
class PostPolicy
  attr_reader :user, :record

  def initialize(user, record)
    @user = user
    @record = record
  end

  def show?
    if user.admin?
      AdminPostPolicy.new(user, record).show?
    else
      false
    end
  end
end
```

What do you think if we'd just add the `policy_class` method to [`PunditScopedResource`](https://github.com/venuu/jsonapi-authorization/blob/v0.5.0/lib/jsonapi/authorization/pundit_scoped_resource.rb) which by default defers the resolving to the resource class?

**Comment by thibaudgg** [comment]
> Having different policy classes based on context seems a bit against the Pundit architecture. Shouldn't you do those checks on the policy level instead of inferring the entire policy class from the current user or something?

Yes correct, I need to take care of that at the Policy level. The issue for use is that our policies really vary on the OAuth2 access_token origin (Public client, Confidential client, User, Operator, Vehicle, ...) and I don't want to end up with a big `case` statement on each of my resource policy methods.

> Having a self.policy_class on the resource overridable seems like a good idea. I wouldn't want to add any parameters to it, though. This is how Pundit itself approaches the issue — no parameters in the policy_class method.

:+1:

> What do you think if we'd just add the policy_class method to PunditScopedResource which by default defers the resolving to the resource class?

Sounds like a good plan.

One last thing, don't you think it would make more sense to send by default the `context` instead of the `user` to the Policy from the Authorizer class? Enforcing the `context[:user]` presence on the `DefaultPunditAuthorizer` seems quite limiting.

**Comment by valscion** [comment]
> Yes correct, I need to take care of that at the Policy level. The issue for use is that our policies really vary on the OAuth2 access_token origin (Public client, Confidential client, User, Operator, Vehicle, ...) and I don't want to end up with a big case statement on each of my resource policy methods.

What if you'd have just one policy which takes care of routing the authorize calls to custom policies? Then you'd only have one possibly big case statement in one place, and all it does is chooses the correct policy class based on the context/user. Something like this:

```ruby
class DelegatePolicy
  def initialize(user, record)
    delegate_policy_class =
      case user
      when PublicClient
        PublicClientPolicy
      when ConfidentialClient
        ConfidentialClientPolicy
      else
        NormalUserPolicy
      end
    @delegate_policy = delegate_policy_class.new(user, record)
  end

  [:index?, :show?, :update?, :create?, :destroy?].each do |action|
    define_method(action) do
      @delegated_policy.public_send(action)
    end
  end
end
```

Would that approach work?

> One last thing, don't you think it would make more sense to send by default the context instead of the user to the Policy from the Authorizer class?

I think it's the responsibility of the Authorizer class to understand where to fetch the user for policies to handle. The `DefaultPunditAuthorizer` class has been structured in a way which makes replacing it very straightforward in your application code, and that's actually the approach we encourage if there's some custom logic on different applications. All that is needed is the custom authorizer class to respond to similar methods as the `DefaultPunditAuthorizer` and you're good to go.

The authorizer class name has the word "Default" for a reason — it's meant to be an easy drop-in for the most common case. If you need more stuff than just the "user" being passed in to your policies, you can always pass something else in the contexts `user` key. For example, we pass a `UserContext` object with more information than just the currently logged in user with it, and then our policies can destructure that object as they please. We just figured that the `user` name is clear enough, even though in our case it might be a bit misleading. Passing the entire `context` is not an option, though, but we're open for better names for the key if you can come up with one :)

**Comment by thibaudgg** [comment]
Great, I agree with everything you said. 
Once we can overwrite the `(Base)Resource#policy_class` and always returns a `DelegatePolicy` we should be good. :+1:
Thanks for your detailed answer.

**Comment by valscion** [comment]
Actually, this change would require major change to the way the authorizer works. We have intentionally removed the resource level from `DefaultPunditAuthorizer` as it should not matter which resource the API call is about as long as the underlying **record** is the same. If you want custom policy classes, you should define them on your record level, like this:

```ruby
class Article < ActiveRecord::Base
  def self.policy_class
    DelegatePolicy
  end
end
```

This already works, as it's how [Pundit looks for policies based on the passed in parameter already](https://github.com/elabs/pundit/blob/v1.1.0/lib/pundit/policy_finder.rb#L79).

Why would it matter authorization-wise from which resource the request originates from? If we have an `ArticleResource` and a `SpecialArticleResource`, and the underlying model for both is `Article` (you probably used [`model_name`](https://github.com/cerebris/jsonapi-resources#model-name) for that, shouldn't requests for those resources be authorized through the same policy?

This sentence particularly is what I'm arguing against (emphasis mine):

> As an application could have different policies for **models and API resources**

I haven't yet come up with a reason _why_ you'd want to have different policies for models and API resources. Resources don't "own" the data, models do, so you should probably handle the authorization on the model level instead of resource level.

In most Rails apps, `jsonapi-resources` isn't the only way to access the underlying models. You would likely already have some forms here and there which are meant to use to change the models. We want to avoid declaring authorization logic on intermediate steps in order to authorize _all_ requests equally. If an `Article` can be modified using normal Rails forms via `/articles/1/edit` and using JR via `PATCH /api/articles/1`, I can't really understand why those two cases shouldn't be treated the same way authorization-wise.

As you have that complex user context logic, you could also use the `DelegatePolicy` approach on your AR model levels.

**Comment by lime** [comment]
I'm on the fence.

Changing the Authorizer interface to take resources instead of models wouldn't complicate things much. We could even have the default authorizer call `._model` on everything and retain the current behaviour, then anyone with more complex needs can make a custom authorizer that works directly on the resource.

I like how the current authorizer is a really thin layer to Pundit, so of course it's a bit frustrating if we (and most users with custom authorizers) have to start littering it with semi-public JR methods like `._model` & `._model_class`.

At the same time, we've tried to keep the dependency on Pundit really light and make it easy to replace it with some other authorization logic. While Pundit usually works on AR classes/models, I don't see why that would have to be the case, especially if you're not using Pundit at all.

**Comment by thibaudgg** [comment]
As the Pundit™ way is to sent the context from the "user" parameter, I think it's good to depend on the model class here.

We can close this issue for me. Thanks for your feedback guys!

**Comment by valscion** [comment]
Thanks for the discussion!

If someone later faces the same need, they're very much free to open a new issue and we can discuss this again. Our approach is not set in stone by any means — this gem is quite young and we're still figuring out the API :smile:
