### ISSUE TITLE
Accessing single related resource

### ISSUE THREAD

**Issue by mkamensky** [venuu/jsonapi-authorization#90]
Hi,

I am getting an error message when trying to access a has_one resource, as in

/foos/7/bar

where a Foo has one Bar. I traced the problem to this line:

https://github.com/venuu/jsonapi-authorization/blob/da04d6cf5ca37c505e6503016141a4413e96c6b2/lib/jsonapi/authorization/authorizing_processor.rb#L94

It appears that the resource class does not define an accessor in this case (i.e., the Foo resource does not have `bar` method). But maybe I'm doing something wrong?

Thanks
Moshe

**Comment by valscion** [comment]
Hi! Thanks for opening an issue :relaxed:

I'm afraid I'm going to need more details on how your resources and models look like. The dummy application this gem uses in the specs does test for a `has_one` relationship, so that should work: https://github.com/venuu/jsonapi-authorization/blob/v1.0.0.alpha6/spec/dummy/app/resources/comment_resource.rb

**Comment by mkamensky** [comment]
Thanks @valscion. So it appears that the difference is that I am using the git version of JR, rather than 0.9. As far as I can see, with the git version, the dummy app fails as well (I'm not sure how one is supposed to run it, none of the policy methods are defined...) I can't figure out what exactly has changed in JR, or why.

**Comment by mkamensky** [comment]
Ok, I think this is a duplicate of #82

**Comment by valscion** [comment]
Ok yeah. We don't yet support the upcoming 0.
